environment:
  nodejs_version: "18"  # Укажите нужную версию Node.js

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm test

build_script:
  - npm run build
