name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # (Опционально) Если нужна сборка (например, для React/Vite)
      - name: Install and build
        run: |
          npm install
          npm run build
      
      # Переносим файлы из `src` в корень (если без сборки)
      - name: Prepare files
        run: |
          mv src/* .
          echo "YourDomain.com" > CNAME
      
      # Загружаем артефакт для GitHub Pages
      - uses: actions/upload-pages-artifact@v2
        with:
          path: src/
      
      # Деплоим
      - uses: actions/deploy-pages@v3
