name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mv src/* .
      - run: echo "Your domain" > CNAME
      - uses: actions/upload-pages-artifact@v2
        with:
          path: src/
      - uses: actions/deploy-pages@v3
